[tool.poetry]
name = "xplat"
version = "0.1.0"
description = "Cross-platform tools for file and image conversion"
authors = ["Neil Johnson <neil@cadent.com>"]
packages = [{ include = "xplat", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
optimize-images = "^1.5.0"
typer = "^0.4.1"
colorama = "^0.4.4"
shellingham = "^1.4.0"
pdf2image = "^1.16.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.950"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
xplat = 'xplat.cli:app'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
